<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.4.1 setup script
 * Date: Tue, 19 Nov 2013 23:01:37 -0600
 */

/* Servers configuration */
$i = 0;

/* Server: pagoda [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'pagoda';
$cfg['Servers'][$i]['host'] = 'tunnel.pagodabox.com';

$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'berenice';
$cfg['Servers'][$i]['password'] = '6pGK4HLc';

/* End of servers configuration */

$cfg['Servers'][$i]['user'] = 'berenice';
$cfg['Servers'][$i]['extension'] = 'mysqli';



$cfg['blowfish_secret'] = '528c420a79f292.44781136';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
